openapi: 3.0.0
info:
  title: ExampleAPI 
  description: API description
  version: 1.0.0
servers:
  - url: 'https://dg99v7cpjl.execute-api.eu-central-1.amazonaws.com/d'
tags:
  - name: Health check
  - name: Auth
  - name: Secret resource
  - name: Custom entity
  - name: Write to s3
paths:
  /health_check:
    get:
      tags:
        - Health check
      summary: "Just to check all's good:)"
      responses:
        '200': 
          description: Successful Health Check
                
  /auth/sign_up:
    post:
      tags:
        - Auth
      summary: "Sign up"
      requestBody:
        required: true
        description: |
          Creates a new user if there is no user with the same email. </br> </br>
          Takes email and password as a request body.
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  minLength: 1
                password:
                  type: string
                  minLength: 1            
            examples:
              'Valid sign up':
                description: |
                  Creates a user with these email and password and sends a verification letter to this email.
                value:
                  email: your.email@example.com
                  password: SomeGoodPass1234
      responses:
        '200': 
          description: Successful sign up
          content:
            application/json:
              example:
                message: "Please check your email for verification link."
        "400":
          description: Bad Request
          content:
            application/json:
              example: 
                message: 'An account with the given email already exists.'
  
  /auth/sign_in:
    get:
      tags:
        - Auth
      summary: 'Get access and refresh tokens'
      description: |
        Operation requires authorization header (Basic email:password)
      responses:
        "200":
          description: Successful Operation
            Returns `AccessToken`, `ExpiresIn`, `RefreshToken`, and `TokenType`.
          content:
            application/json:
              example: 
                AccessToken: some.long.string
                ExpiresIn: 3600
                RefreshToken: other.long.string
                TokenType: Bearer
        '401':
          description: Authorization header is missing or invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response_401'
      security:
        - basicAuth: []
        
  /auth/refresh:
    get:
      tags:
        - Auth
      summary: "Refresh access token"
      description: |
        Operation requires authorization header (Bearer) with `RefreshToken` from `SignIn` responce
      responses:
        "200":
          description: Successful Operation
            Returns new `AccessToken`, `ExpiresIn` and `TokenType`.
          content:
            application/json:
              example: 
                AccessToken: some.long.string
                ExpiresIn: 3600
                TokenType: Bearer
        '401':
          description: Authorization header is missing or invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response_401'
      security:
        - bearerAuth: []

  /secret_resource:
    get:
      tags:
        - Secret resource
      summary: "Can be accessed only with access token"
      description: "Operation requires authorization header (Bearer)"
      responses:
        '200': 
          description: Successful Operation
      security:
        - bearerAuth: []
    
  /doggos:
    get: 
      tags:
        - Custom entity
      summary: Get all entities
      responses:
        '200': 
          description:  Successful Operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  description: List of entities
    post:
      tags:
        - Custom entity
      summary: Add a new entity
      requestBody:
        required: true
        description: |
          Creates a new entity.</br> </br>
          __Table 1.__  Request body structure:
            | Field | Description |
            | ------- | -------- |
            | `email*` | Required. Entity's email. |
            | `message*`| Required. Entity's description. Min length is 1, max length is 500. |
            | `rating*` | Required numeric between 1 and 10. |
            | `birthdate*` | Required string date in format YYYY-MM-DD. |
            | `need_feedback` | Non-required boolean that describes entity. Default value is false.|
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/entity'      
            example:
              email: donny@example.com
              message: Hi, you all!
              rating: 9
              birthdate: "1992-08-17"
              need_feedback: true
      responses:
        '201': 
          description: Successful Operation
          content:
            application/json:
              example:
                uid: "some-uid-here"
        '400': 
          description: Bad Request
          content:
            application/json:
              example:
                email: "Record with email 'donny@example.com' already exists"
      security:
        - bearerAuth: []
  
  
  /doggos/{uid}:
    get: 
      tags:
        - Custom entity
      summary: Get one entity by username
      parameters:
        - in: path
          name: uid
          schema:
            type: string
          required: true
          description: String uid that is case-sensitive
      responses:
        '200': 
          description: |
            Successful Operation </br> 
            __Table 2.__  Successfull response structure:
            | Field | Description |
            | ------- | -------- |
            | `email*` | Required. Entity's email. |
            | `message*`| Required. Entity's description. Min length is 1, max length is 500. |
            | `rating*` | Required numeric between 1 and 10. |
            | `birthdate*` | Required string date in format YYYY-MM-DD. |
            | `need_feedback` | Non-required boolean that describes entity. Default value is false.|
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/entity'
              example:
                uid: "some-uid-here"
                email: larry@example.com
                description: Good enough
                value: 22
                date: "1991-10-22"
                is_good_boy: true
        '404':
          description: Entity with given uid was not found.
          content: 
            application/json:
              example:
                message: No such entity.
    delete:  
      tags:
        - Custom entity
      summary: Delete one entity
      parameters:
        - in: path
          name: uid
          schema:
            type: string
          required: true
          description: String uid that is case-sensitive
      responses:
        '200': 
          description: Successful Deletion
          content:
            application/json:
              example:
                message: "Deleted succesfully."
      security:
        - bearerAuth: []
  
  /write_to_bucket:
    post: 
      tags:
        - Write to s3
      summary: Add an entry to the file from s3 bucket
      requestBody:
        required: true
        description: |
          Writes a new entry to a file in s3 bucket.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/entry'      
            example:
              entry: This is my first entry!
      responses:
        '200': 
          description:  Successful Operation
          content:
            application/json:
              example:
                message: Added successfully
        
components:
  schemas:
    'entity':
      type: object
      additionalProperties: false
      required:
        - email
        - description
        - value
        - date
      properties:
        email:
          type: string
          format: email
          minLength: 1
        message:
          type: string
          minLength: 1
          maxLength: 500
        rating:
          type: integer
          minimum: 1
          maximum: 10
        birthdate:
          type: string
        need_feedback:
          type: boolean
          default: false
          
    'entry':
      type: object
      additionalProperties: false
      required:
        - entry
      properties:
        entry:
          type: string
    
    'response_401':
      type: object
      properties:
        message:
          type: string
          example:
            "Unauthorized"
          
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 
